In [13]:
#############################################################
# Rotina para converter DD° MM' SS.S' ou DD° MM.M' em DD.DDDD
#############################################################

import pandas as pd
import re

#https://stackoverflow.com/questions/33997361
def dms2dd(s):
    # example: s = """0°51'56.29"S"""
    degrees, minutes, seconds, direction = re.split('[°\'"]+', s)
    dd = float(degrees) + float(minutes)/60 + float(seconds)/(60*60);
    if direction in ('S','W'):
        dd*= -1
    return dd

def dm2dd(s):
    # example: s = """0°56.29'S"""
    degrees, minutes, direction = re.split('[°\'"]+', s)
    dd = float(degrees) + float(minutes)/60;
    if direction in ('S','W'):
        dd*= -1
    return dd

In [8]:
# Exemplo DD°MM'SS.S"
df1 = pd.DataFrame({'CPO': {0: 'Raya', 1: 'Raya'},
 'Latitude': {0: '0°51\'56.29"S', 1: '1°23\'39.29"S'},
 'Longitude': {0: '101°26\'46.29"E', 1: '101°35\'30.45"E'},
 'PKO': {0: 'X', 1: 'X'},
 'ParentCompany': {0: 'Incasi', 1: 'Incasi'}})
df1['Latitude'] = df1['Latitude'].apply(dms2dd)
df1['Longitude'] = df1['Longitude'].apply(dms2dd)

In [16]:
# Exemplo DD°MM.M'
df2 = pd.read_csv('c:\\Users\\Marcelo\\Documents\\Projetos\\USSV\\baiaBabitonga\\maregrafos.csv', header = 0 )
df2['Latitude'] = df2['Lat'].apply(dm2dd)
df2['Longitude'] = df2['Long'].apply(dm2dd)

,Long,Lat,Estacao,Latitude,Longitude
0,48°46.4'W,26°17.5'S,60222_Joinville_Iate_Clube,-26.291667,-48.773333
1,48°33.7'W,26°10.4'S,60266_Terminal_Gas_Sul,-26.173333,-48.561667
2,48°49.4'W,26°18.5'S,60226_Iate_Clube_Boa_Vista,-26.308333,-48.823333
3,48°36.4'W,26°11.1'S,60219_Porto_de_Itapoa,-26.185000,-48.606667
4,48°42.5'W,26°15.1'S,60221_Ilha_da_Rita,-26.251667,-48.708333
5,48°38.5'W,26°14.7'S,60225_Clube_Náutico_Cruzeiro_Sul,-26.245000,-48.641667
6,48°29.1'W,26°10.7'S,60208_Ilha_da_Paz,-26.178333,-48.485000

In [19]:
df.to_csv('c:\\Users\\Marcelo\\Documents\\Projetos\\USSV\\baiaBabitonga\\maregrafosdd_dddd.csv')